import express from "express";
import notFound from "./middleware/not-found.middleware";
import errorMiddleware from "./middleware/error.middleware";
import userRoutes from "./routes/user.routes";
import categoryRoutes from "./routes/category.routes";
import brandRoutes from "./routes/brand.routes";
import productRoutes from "./routes/product.routes";
import varientRoutes from "./routes/varient.routes";
import inventoryRoutes from "./routes/inventory.routes";
const app = express();
app.use(express.json());
app.use("/api/users", userRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/brands", brandRoutes);
app.use("/api/products", productRoutes);
app.use("/api/varients", varientRoutes);
app.use("/api/inventories", inventoryRoutes);
app.use(notFound);
app.use(errorMiddleware);
export default app;
